- 1.1.8+dfsg-2
- _NAME: MX Master 3S
  _absent: [hi-res-scroll, lowres-scroll-mode, onboard_profiles, report_rate, pointer_speed, speed-change, backlight, backlight-timed, fn-swap, persistent-remappable-keys,
    disable-keyboard-keys, crown-smooth, divert-crown, divert-gkeys, m-key-leds, mr-key-led, multiplatform, gesture2-gestures, gesture2-divert, gesture2-params,
    sidetone, equalizer]
  _battery: 4100
  _modelId: B03400000000
  _sensitive: {change-host: false, divert-keys: false, dpi: false, hires-smooth-resolution: false, reprogrammable-keys: false, scroll-ratchet: false, smart-shift: false,
    thumb-scroll-invert: false, thumb-scroll-mode: false}
  _unitId: 91AF3AC6
  change-host: null
  divert-keys: {82: 0, 83: 0, 86: 0, 195: 2, 196: 2}
  dpi: 3000
  hires-scroll-mode: false
  hires-smooth-invert: false
  hires-smooth-resolution: true
  reprogrammable-keys: {80: 80, 81: 81, 82: 82, 83: 83, 86: 86, 195: 86, 196: 196}
  scroll-ratchet: 2
  smart-shift: 21
  thumb-scroll-invert: false
  thumb-scroll-mode: false
